name: 'consejonl'
version: '1.0.0'
config-version: 2

profile: 'consejonl'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  consejonl:
    +quote_columns: true
    +persist_docs:
      relation: true
      columns: true

    # Tier 1 (staging) en ODW
    tier_1_staging:
      +database: "{{ env_var('DBT_ODW_DATABASE', env_var('SNOWFLAKE_DATABASE')) }}"
      +schema: "staging"
      +materialized: view

    # Tier 2 (intermediate) en ODW
    tier_2_intermediate:
      +database: "{{ env_var('DBT_ODW_DATABASE', env_var('SNOWFLAKE_DATABASE')) }}"
      +schema: "intermediate"
      +materialized: table

    # Tier 3 (marts) en CDW
    tier_3_marts:
      +database: "{{ env_var('DBT_CDW_DATABASE', env_var('SNOWFLAKE_DATABASE')) }}"
      +schema: "marts"
      +materialized: table

    audit:
      +database: "{{ env_var('DBT_CDW_DATABASE', env_var('SNOWFLAKE_DATABASE')) }}"
      +schema: "audit"
      +materialized: table

# (Opcional) Para que nuestra macro 'generate_schema_name' pueda tomar control
dispatch:
  - macro_namespace: dbt
    search_order: ['consejonl', 'dbt']
